import { EXERCISE_SEED } from '@/db/seed';
import type { CatalogExercise, CatalogLocale, CatalogSnapshot } from './types';

const LOCALE_LABEL: Record<CatalogLocale, string> = {
  en: 'Exercise',
  ko: '운동',
  es: 'Ejercicio',
  'zh-Hans': '动作',
};

/** Test-only valid payload. Production always consumes the generated byte-exact asset. */
export function catalogFixture(overrides: Partial<CatalogSnapshot> = {}): CatalogSnapshot {
  return {
    schemaVersion: '1.0.0',
    catalogVersion: '1.0.0',
    effectiveAt: '2026-07-14T00:00:00Z',
    defaultLocale: 'en',
    supportedLocales: ['en', 'ko', 'es', 'zh-Hans'],
    searchNormalization: 'search-v1',
    exercises: EXERCISE_SEED.map((seed, index) => exerciseFixture(seed.id, index + 1, seed.type)),
    ...overrides,
  };
}

export function exerciseFixture(
  id: string,
  displayOrder: number,
  exerciseType: 'strength' | 'cardio' = 'strength',
): CatalogExercise {
  const perSide = new Set([
    'bulgarian_split_squat',
    'single_arm_db_row',
    'walking_lunge',
    'step_platform_step_up',
    'dead_bug',
    'side_plank_hip_lift',
    'cable_anti_rotation_press',
    'seated_trunk_rotation',
    'dumbbell_suitcase_march',
    'dumbbell_single_leg_hip_hinge',
  ]).has(id);
  const isPlank = id === 'plank';
  const localizations = Object.fromEntries(
    (['en', 'ko', 'es', 'zh-Hans'] as const).map((locale) => [
      locale,
      {
        displayName: `${LOCALE_LABEL[locale]} ${displayOrder}`,
        aliases: [`${LOCALE_LABEL[locale]} alias ${displayOrder}`],
      },
    ]),
  ) as CatalogExercise['localizations'];
  return {
    id,
    recordRevision: 1,
    status: 'active',
    effectiveFrom: '2026-07-14T00:00:00Z',
    effectiveTo: null,
    replacementId: null,
    displayOrder,
    localizations,
    exerciseType,
    isBodyweight: false,
    equipment: { required: exerciseType === 'cardio' ? ['treadmill'] : ['barbell'], optional: [] },
    movementPattern: exerciseType === 'cardio' ? 'locomotion_run' : 'horizontal_push',
    difficulty: 'beginner',
    primaryBodyRegions: exerciseType === 'cardio' ? [] : ['chest'],
    secondaryBodyRegions: exerciseType === 'cardio' ? [] : ['triceps'],
    defaultPrescription: exerciseType === 'cardio'
      ? {
          sets: 1,
          trackingMode: 'duration',
          countingConvention: 'not_applicable',
          target: { unit: 'minutes', low: 10, high: 20 },
        }
      : isPlank
        ? {
            sets: 3,
            trackingMode: 'duration',
            countingConvention: 'total',
            target: { unit: 'seconds', low: 30, high: 60 },
          }
        : {
            sets: 3,
            trackingMode: 'reps',
            countingConvention: perSide ? 'per_side' : 'total',
            target: { unit: 'reps', low: 8, high: 12 },
          },
    provenance: {
      classification: 'original_editorial',
      reviewStatus: 'unreviewed',
      reviewMethod: 'none',
      reviewedByRole: null,
      reviewEvidence: null,
      reviewedAt: null,
      containsThirdPartyCopy: false,
      sources: [],
    },
  };
}
