const { withAppDelegate } = require('@expo/config-plugins');

const CALL_MARKER = '// @generated by withReploomIosCompliance: backup protection call';
const METHOD_MARKER = '// @generated by withReploomIosCompliance: backup protection method';

const METHOD = `  ${METHOD_MARKER}
  /// The SQLite database can contain Apple Health-derived summaries. Create its directory before
  /// Expo opens the database, exclude the directory and sidecars from backup, and apply complete
  /// file protection. Failure is logged without blocking launch.
  private func protectLocalDatabaseFromBackup() {
    do {
      let documents = try FileManager.default.url(
        for: .documentDirectory,
        in: .userDomainMask,
        appropriateFor: nil,
        create: true)
      let sqliteDirectory = documents.appendingPathComponent("SQLite", isDirectory: true)
      try FileManager.default.createDirectory(
        at: sqliteDirectory,
        withIntermediateDirectories: true,
        attributes: [.protectionKey: FileProtectionType.complete])
      let existingFiles = try FileManager.default.contentsOfDirectory(
        at: sqliteDirectory,
        includingPropertiesForKeys: nil,
        options: [])
      for item in [sqliteDirectory] + existingFiles {
        do {
          var protectedItem = item
          var values = URLResourceValues()
          values.isExcludedFromBackup = true
          try protectedItem.setResourceValues(values)
          try FileManager.default.setAttributes(
            [.protectionKey: FileProtectionType.complete],
            ofItemAtPath: protectedItem.path)
        } catch {
          NSLog("[privacy] failed to protect SQLite item %@: %@", item.lastPathComponent, String(describing: error))
        }
      }
    } catch {
      NSLog("[privacy] failed to protect SQLite from backup: %@", String(describing: error))
    }
  }

`;

function patchSwiftAppDelegate(source) {
  let contents = source;

  if (!contents.includes(CALL_MARKER)) {
    const launchBody = /(didFinishLaunchingWithOptions launchOptions:[\s\S]*?\) -> Bool \{\n)(\s*)/;
    if (!launchBody.test(contents)) {
      throw new Error('Reploom compliance plugin could not find the iOS launch method');
    }
    contents = contents.replace(
      launchBody,
      (_, signature, indentation) => `${signature}${indentation}${CALL_MARKER}\n${indentation}protectLocalDatabaseFromBackup()\n\n${indentation}`,
    );
  }

  if (!contents.includes(METHOD_MARKER)) {
    const linkingAnchor = '  // Linking API\n';
    if (!contents.includes(linkingAnchor)) {
      throw new Error('Reploom compliance plugin could not find the AppDelegate insertion anchor');
    }
    contents = contents.replace(linkingAnchor, `${METHOD}${linkingAnchor}`);
  }

  contents = contents.replace(
    '// needed to return the correct URL for expo-dev-client.',
    '// Return the correct bundle URL for Expo Router in development and Release.',
  );

  return contents;
}

function withReploomIosCompliance(config) {
  return withAppDelegate(config, (nextConfig) => {
    if (nextConfig.modResults.language !== 'swift') {
      throw new Error('Reploom iOS compliance requires a Swift AppDelegate');
    }
    nextConfig.modResults.contents = patchSwiftAppDelegate(nextConfig.modResults.contents);
    return nextConfig;
  });
}

module.exports = withReploomIosCompliance;
module.exports.patchSwiftAppDelegate = patchSwiftAppDelegate;
