const fs = require('node:fs');
const path = require('node:path');
const {
  IOSConfig,
  withAppDelegate,
  withDangerousMod,
  withXcodeProject,
} = require('@expo/config-plugins');

const CALL_MARKER = '// @generated by withReploomIosCompliance: backup protection call';
const METHOD_MARKER = '// @generated by withReploomIosCompliance: backup protection method';
const STOREKIT_SOURCE = path.join('storekit', 'Reploom.storekit');

const METHOD = `  ${METHOD_MARKER}
  /// The SQLite database can contain Apple Health-derived summaries. Create its directory before
  /// Expo opens the database, exclude the directory and sidecars from backup, and apply complete
  /// file protection. Failure is logged without blocking launch.
  private func protectLocalDatabaseFromBackup() {
    do {
      let documents = try FileManager.default.url(
        for: .documentDirectory,
        in: .userDomainMask,
        appropriateFor: nil,
        create: true)
      let sqliteDirectory = documents.appendingPathComponent("SQLite", isDirectory: true)
      try FileManager.default.createDirectory(
        at: sqliteDirectory,
        withIntermediateDirectories: true,
        attributes: [.protectionKey: FileProtectionType.complete])
      let existingFiles = try FileManager.default.contentsOfDirectory(
        at: sqliteDirectory,
        includingPropertiesForKeys: nil,
        options: [])
      for item in [sqliteDirectory] + existingFiles {
        do {
          var protectedItem = item
          var values = URLResourceValues()
          values.isExcludedFromBackup = true
          try protectedItem.setResourceValues(values)
          try FileManager.default.setAttributes(
            [.protectionKey: FileProtectionType.complete],
            ofItemAtPath: protectedItem.path)
        } catch {
          NSLog("[privacy] failed to protect SQLite item %@: %@", item.lastPathComponent, String(describing: error))
        }
      }
    } catch {
      NSLog("[privacy] failed to protect SQLite from backup: %@", String(describing: error))
    }
  }

`;

function patchSwiftAppDelegate(source) {
  let contents = source;

  if (!contents.includes(CALL_MARKER)) {
    const launchBody = /(didFinishLaunchingWithOptions launchOptions:[\s\S]*?\) -> Bool \{\n)(\s*)/;
    if (!launchBody.test(contents)) {
      throw new Error('Reploom compliance plugin could not find the iOS launch method');
    }
    contents = contents.replace(
      launchBody,
      (_, signature, indentation) => `${signature}${indentation}${CALL_MARKER}\n${indentation}protectLocalDatabaseFromBackup()\n\n${indentation}`,
    );
  }

  if (!contents.includes(METHOD_MARKER)) {
    const linkingAnchor = '  // Linking API\n';
    if (!contents.includes(linkingAnchor)) {
      throw new Error('Reploom compliance plugin could not find the AppDelegate insertion anchor');
    }
    contents = contents.replace(linkingAnchor, `${METHOD}${linkingAnchor}`);
  }

  contents = contents.replace(
    '// needed to return the correct URL for expo-dev-client.',
    '// Return the correct bundle URL for Expo Router in development and Release.',
  );

  return contents;
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
}

function findNativeTargetId(projectSource, projectName) {
  const targetPattern = new RegExp(
    `([A-F0-9]{24}) /\\* ${escapeRegExp(projectName)} \\*/ = \\{\\s*isa = PBXNativeTarget;`,
    'u',
  );
  const match = projectSource.match(targetPattern);
  if (!match) throw new Error(`Reploom compliance plugin could not find the ${projectName} native target`);
  return match[1];
}

function storeKitQaScheme(projectName, nativeTargetId) {
  const buildable = `            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "${nativeTargetId}"
               BuildableName = "${projectName}.app"
               BlueprintName = "${projectName}"
               ReferencedContainer = "container:${projectName}.xcodeproj">
            </BuildableReference>`;
  return `<?xml version="1.0" encoding="UTF-8"?>
<Scheme LastUpgradeVersion="2700" version="1.3">
   <BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES">
      <BuildActionEntries>
         <BuildActionEntry buildForTesting="YES" buildForRunning="YES" buildForProfiling="YES" buildForArchiving="YES" buildForAnalyzing="YES">
${buildable}
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <TestAction buildConfiguration="Debug" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" shouldUseLaunchSchemeArgsEnv="YES">
      <Testables></Testables>
   </TestAction>
   <LaunchAction buildConfiguration="Release" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" launchStyle="0" useCustomWorkingDirectory="NO" ignoresPersistentStateOnLaunch="NO" debugDocumentVersioning="YES" debugServiceExtension="internal" allowLocationSimulation="YES">
      <BuildableProductRunnable runnableDebuggingMode="0">
${buildable}
      </BuildableProductRunnable>
      <StoreKitConfigurationFileReference identifier="../../${projectName}/Products.storekit"></StoreKitConfigurationFileReference>
   </LaunchAction>
   <ProfileAction buildConfiguration="Release" shouldUseLaunchSchemeArgsEnv="YES" savedToolIdentifier="" useCustomWorkingDirectory="NO" debugDocumentVersioning="YES">
      <BuildableProductRunnable runnableDebuggingMode="0">
${buildable}
      </BuildableProductRunnable>
   </ProfileAction>
   <AnalyzeAction buildConfiguration="Debug"></AnalyzeAction>
   <ArchiveAction buildConfiguration="Release" revealArchiveInOrganizer="YES"></ArchiveAction>
</Scheme>
`;
}

function validateStoreKitConfiguration(contents) {
  const configuration = JSON.parse(contents);
  const subscriptions = configuration.subscriptionGroups?.flatMap((group) => group.subscriptions ?? []) ?? [];
  const product = subscriptions.find(
    (subscription) => subscription.productID === 'ai.daeseon.reploom.pro.monthly.v1',
  );
  const plan = product?.billingPlans?.find((candidate) => candidate.isEnabled === true);
  if (
    configuration.version?.major !== 6
    || product?.recurringSubscriptionPeriod !== 'P1M'
    || product?.familyShareable !== false
    || product?.introductoryOffers?.length !== 0
    || product?.adHocOffers?.length !== 0
    || product?.codeOffers?.length !== 0
    || product?.winbackOffers?.length !== 0
    || plan?.billingPlanType !== 'BILLED_UPFRONT'
    || plan?.displayPrice !== '4.99'
    || configuration.settings?._askToBuyEnabled !== false
    || configuration.settings?._billingGracePeriodEnabled !== false
    || configuration.settings?._billingIssuesEnabled !== false
    || configuration.settings?._failTransactionsEnabled !== false
  ) {
    throw new Error('Reploom StoreKit QA configuration does not match the monthly subscription contract');
  }
}

function synchronizeNativeBuildVersion(project, projectName, buildNumber) {
  if (!/^\d+(?:\.\d+){0,2}$/u.test(buildNumber)) {
    throw new Error('Reploom compliance plugin requires a numeric iOS build number');
  }

  const [, nativeTarget] = IOSConfig.Target.findNativeTargetByName(project, projectName);
  const configurations = IOSConfig.XcodeUtils.getBuildConfigurationsForListId(
    project,
    nativeTarget.buildConfigurationList,
  );
  if (configurations.length === 0) {
    throw new Error(`Reploom compliance plugin could not find build configurations for ${projectName}`);
  }
  for (const [, configuration] of configurations) {
    configuration.buildSettings.CURRENT_PROJECT_VERSION = buildNumber;
  }
  return project;
}

function writeStoreKitQaArtifacts({ projectRoot, platformProjectRoot, projectName }) {
  const sourcePath = path.join(projectRoot, STOREKIT_SOURCE);
  const contents = fs.readFileSync(sourcePath, 'utf8');
  validateStoreKitConfiguration(contents);
  const projectFile = path.join(platformProjectRoot, `${projectName}.xcodeproj`, 'project.pbxproj');
  const nativeTargetId = findNativeTargetId(fs.readFileSync(projectFile, 'utf8'), projectName);

  const configurationPath = path.join(platformProjectRoot, projectName, 'Products.storekit');
  const schemePath = path.join(
    platformProjectRoot,
    `${projectName}.xcodeproj`,
    'xcshareddata',
    'xcschemes',
    `${projectName}-StoreKit-QA.xcscheme`,
  );
  fs.mkdirSync(path.dirname(configurationPath), { recursive: true });
  fs.mkdirSync(path.dirname(schemePath), { recursive: true });
  fs.writeFileSync(configurationPath, contents);
  fs.writeFileSync(schemePath, storeKitQaScheme(projectName, nativeTargetId));
}

function withReploomIosCompliance(config) {
  const withDelegate = withAppDelegate(config, (nextConfig) => {
    if (nextConfig.modResults.language !== 'swift') {
      throw new Error('Reploom iOS compliance requires a Swift AppDelegate');
    }
    nextConfig.modResults.contents = patchSwiftAppDelegate(nextConfig.modResults.contents);
    return nextConfig;
  });
  const withSynchronizedBuildVersion = withXcodeProject(withDelegate, (nextConfig) => {
    const { projectName } = nextConfig.modRequest;
    const buildNumber = nextConfig.ios?.buildNumber;
    if (!projectName || !buildNumber) {
      throw new Error('Reploom compliance plugin requires an iOS project name and build number');
    }
    nextConfig.modResults = synchronizeNativeBuildVersion(
      nextConfig.modResults,
      projectName,
      buildNumber,
    );
    return nextConfig;
  });
  return withDangerousMod(withSynchronizedBuildVersion, ['ios', (nextConfig) => {
    const { projectRoot, platformProjectRoot, projectName } = nextConfig.modRequest;
    if (!projectName) throw new Error('Reploom compliance plugin requires an iOS project name');
    writeStoreKitQaArtifacts({ projectRoot, platformProjectRoot, projectName });
    return nextConfig;
  }]);
}

module.exports = withReploomIosCompliance;
module.exports.patchSwiftAppDelegate = patchSwiftAppDelegate;
module.exports.findNativeTargetId = findNativeTargetId;
module.exports.storeKitQaScheme = storeKitQaScheme;
module.exports.synchronizeNativeBuildVersion = synchronizeNativeBuildVersion;
module.exports.validateStoreKitConfiguration = validateStoreKitConfiguration;
